language: python
python:
  - 2.7
  - 3.6
cache: pip
install:
  - pip install -r requirements-dev.txt
before_script:
  - cd tests
  - export PYTHONPATH="$PYTHONPATH:.."
script:
  - python -m unittest discover -v
